### PR TITLE
MIT LICENSE added

### PR DESCRIPTION
**Pull request by kbzowski**

### CODE REVIEW

**Comment by cspotcode** [comment]
Should also be added to package.json and bundled in the npmjs package?

Similar to the `license` and `files` fields here? https://github.com/cspotcode/outdent/blob/main/package.json

**Comment by SnowMarble** [comment]
I've looked up [document](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files) and think LICENCE file also need to be added. [license filed](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license) as well

files:
>Certain files are always included, regardless of settings:
>
>    package.json
>    README
>    CHANGES / CHANGELOG / HISTORY
>    LICENSE / LICENCE
>    NOTICE
>    The file in the "main" field

license:
> You should specify a license for your package so that people know how they are permitted to use it, and any restrictions you're placing on it.

**Comment by SnowMarble** [comment]
I think we only need to fill license field. LICENSE file is automatically included.
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files
>You should specify a license for your package so that people know how they are permitted to use it, and any restrictions you're placing on it.

**Comment by kbzowski** [comment]
For completeness, a `license` field was added to package.json

**Comment by kbzowski** [comment]
@cspotcode I think you can merge it now.

**Comment by kbzowski** [comment]
+1 :)

**Pull request merged**
